### ISSUE TITLE
API Endpoint URL

### ISSUE THREAD

**Issue by 100ideas** [Behavioral-Technology-Group/Pavlok_Node_Module#1]
Hi,

should we be using https://pavlok.herokuapp.com/, http://pavlok-stage.herokuapp.com/oauth/applications/, or http://pavlok-mvp.herokuapp.com/oauth/applications/?

I am not sure the user account I registered in the pavlok iphone app is being associated with the accounts I have made on those servers. I used the same email address but haven't been able to make the iphone app respond to my API requests.

Thanks

**Comment by DanielRondeau** [comment]
We should be using http://pavlok-mvp.herokuapp.com/oauth/applications

**Comment by maclyn** [comment]
Pretty sure this is fixed now, so I'm going to close this unless anyone has an objection.
