### ISSUE TITLE
Tutorial broken

### ISSUE THREAD

**Issue by rodrigobdz** [Behavioral-Technology-Group/Pavlok_Node_Module#19]
Following the instructions results in the following error:

<img width="544" alt="image" src="https://github.com/Behavioral-Technology-Group/Pavlok_Node_Module/assets/14152377/29b3e705-b6cd-4e0f-94f1-b8c624df7814">

---

## Reproduction steps

1. Create Pavlok application
    
     <img width="368" alt="image" src="https://github.com/Behavioral-Technology-Group/Pavlok_Node_Module/assets/14152377/c6a2fd8f-ae5c-4372-9609-bd42308f929d">

2. Init Pavlok project

```sh
mkdir pavlok-test
cd pavlok-test
yarn init
yarn add pavlok
vim index.js
```

Contents of `index.js`
The placeholders `CLIENT_ID` and `CLIENT_SECRET` were replaced, as instructed in the readme.
```js
const pavlok = require('pavlok');

pavlok.init(CLIENT_ID, CLIENT_SECRET);
pavlok.login(function (result, code) {
	if (result) {
		console.log("Code is " + code);
		pavlok.vibrate(); // or you can call other methods like beep() or zap()
	}
});
```
3. Run `index.js`

4. Opens browser asking for authorization

     <img width="2069" alt="image" src="https://github.com/Behavioral-Technology-Group/Pavlok_Node_Module/assets/14152377/36be24de-8438-4fb2-b608-d70fac0bc4fe">

5. Clicking on `Authorize` redirects to `https://app.pavlok.com/auth/pavlok/result?code=<CODE>` with `<CODE>` here as placeholder and error is shown.

**Comment by YasserDRIF** [comment]
Hello, This model has been deprecated, You can find details about access to the API directly here
https://pavlok.readme.io/reference/auth_login_api_v5_users_login_post
You can use it to login, get user info and also send stimulus to a user

**Comment by rodrigobdz** [comment]
@YasserDRIF Thanks for sharing the link to the new documentation. 

Where is this linked on the Pavlok website? I searched online before submitting the issue but couldn't find it.
